#!/usr/bin/env bash
#
# One command from a fresh Ubuntu/Debian server to MJLsearch running as services.
#
#   sudo ./deploy/setup-server.sh                 # install, build, enable, start
#   sudo ./deploy/setup-server.sh --no-start      # install everything, start nothing
#   sudo ./deploy/setup-server.sh --no-crawl      # everything except the crawl unit
#   sudo ./deploy/setup-server.sh --user mjlsearch
#   sudo ./deploy/setup-server.sh --help
#
# What it does, in order:
#
#   1. apt: the C/C++ toolchain, clang's libclang, and curl. Building the crawler
#      compiles the RocksDB C++ sources the crate bundles *and* runs rust-bindgen over
#      its headers -- the generated bindings in the build directory say "automatically
#      generated by rust-bindgen 0.72.1", which is the evidence rather than a guess --
#      so `build-essential` and `libclang-dev` are both required. cmake is *not*, even
#      though it is in the dependency graph: aws-lc-sys (rustls's crypto backend) builds
#      with the C compiler here and prints "Building with: CC". Nothing else from apt is
#      needed, because uv brings its own Python 3.12 along with its headers, which is
#      what the PyO3 extension is built against, and rustup brings Rust.
#   2. A user to run as: `--user` if given, otherwise the human who invoked sudo --
#      their own server, their own checkout, no new account to reason about. `--user`
#      for a name that does not exist creates a system account and hands it the app
#      directory, which is the right shape for a machine nobody logs into.
#   3. Toolchain as that user: rustup (minimal profile) and uv, both into its home.
#      `uv sync` then builds the Rust extension and cargo builds the two binaries.
#   4. A seed list, if there is not one already, from the sites' own sitemaps.
#   5. /etc/default/mjlsearch -- ports and switches, written once and never overwritten.
#   6. systemd units, rendered from deploy/systemd/*.service so the paths in them come
#      from here rather than from a text file someone edited.
#
# It is idempotent: a second run re-installs nothing that is already there, re-renders
# the units (so a change to a unit file takes effect), and restarts the services.
#
# Running it again after `git pull` is the update path. Nothing here is a git operation:
# it expects the checkout to have been updated already, and it never touches your
# working tree.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
UNIT_DIR="$SCRIPT_DIR/systemd"
ENV_FILE="/etc/default/mjlsearch"
ENV_TEMPLATE="$SCRIPT_DIR/mjlsearch.env.example"

SERVICE_USER=""
SERVICE_GROUP=""
SERVICE_HOME=""
CREATE_USER=0
START=1
CRAWL=1

step() { printf '\n==> %s\n' "$1"; }
note() { printf '    %s\n' "$1"; }
die() { printf '\nERROR: %s\n' "$1" >&2; exit 1; }

for arg in "$@"; do
  case "$arg" in
    --user=*) SERVICE_USER="${arg#--user=}" ;;
    --app-dir=*) APP_DIR="${arg#--app-dir=}" ;;
    --no-start) START=0 ;;
    --no-crawl) CRAWL=0 ;;
    -h|--help) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown option: $arg (try --help)" ;;
  esac
done

# `--user NAME` in either spelling: the flag form above, or the older space-separated one.
prev=""
for arg in "$@"; do
  if [ "$prev" = "--user" ]; then SERVICE_USER="$arg"; fi
  prev="$arg"
done

step "checking we are root and looking at the machine"
if [ "$(id -u)" != "0" ]; then
  die "run this with sudo: sudo $0"
fi
note "app directory: $APP_DIR"
[ -d "$APP_DIR/crates" ] || die "$APP_DIR does not look like an MJLsearch checkout (no crates/)"

if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  note "system: ${PRETTY_NAME:-unknown}"
  case "${ID:-}${ID_LIKE:-}" in
    *debian*|*ubuntu*) : ;;
    *) note "warning: this script installs packages with apt; ${ID:-this} may need different names" ;;
  esac
fi

if ! command -v apt-get >/dev/null 2>&1; then
  die "apt-get is missing, so this script cannot install build-essential. Install a C/C++ toolchain, cargo, uv and systemd by hand, then run ./start.sh."
fi

step "installing packages (apt)"
# --no-install-recommends keeps this to what is actually needed: a compiler and linker
# (build-essential), libclang for rust-bindgen (libclang-dev, which is also what brings
# the clang binary in), a trust store for the crawler's rustls -- it uses the OS store on
# purpose -- and xz for uv's Python builds.
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends \
  build-essential clang libclang-dev ca-certificates curl xz-utils | sed 's/^/    /'
note "build-essential clang libclang-dev ca-certificates curl xz-utils are present"

step "choosing the user the services run as"
if [ -z "$SERVICE_USER" ]; then
  if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    SERVICE_USER="$SUDO_USER"
  else
    SERVICE_USER="$(stat -c '%U' "$APP_DIR")"
  fi
fi

if id -u "$SERVICE_USER" >/dev/null 2>&1; then
  SERVICE_GROUP="$(id -gn "$SERVICE_USER")"
  SERVICE_HOME="$(getent passwd "$SERVICE_USER" | cut -d: -f6)"
  note "existing user $SERVICE_USER (group $SERVICE_GROUP, home $SERVICE_HOME)"
else
  # A name that does not exist is a request for a service account, not a typo to fail on:
  # a server nobody logs into should not run the search engine as whoever happened to
  # install it.
  note "user $SERVICE_USER does not exist -- creating a system account"
  useradd --system --create-home --home-dir "/var/lib/$SERVICE_USER" \
    --shell /usr/sbin/nologin "$SERVICE_USER"
  SERVICE_GROUP="$(id -gn "$SERVICE_USER")"
  SERVICE_HOME="$(getent passwd "$SERVICE_USER" | cut -d: -f6)"
  CREATE_USER=1
  note "created $SERVICE_USER (home $SERVICE_HOME)"
fi

if [ "$CREATE_USER" = "1" ] || [ "$(stat -c '%U' "$APP_DIR")" != "$SERVICE_USER" ]; then
  if [ "$CREATE_USER" = "1" ]; then
    # Only for an account this script just made: the directory is handed over whole,
    # because a build writes into target/ and the services write into data/ and logs/.
    note "handing $APP_DIR to $SERVICE_USER"
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$APP_DIR"
  else
    # Never chown a checkout someone else owns: it is their working tree, and doing it
    # silently would be a surprise in the other direction.
    missing=0
    for dir in data logs seeds target; do
      mkdir -p "$APP_DIR/$dir"
      if [ "$(stat -c '%U' "$APP_DIR/$dir")" != "$SERVICE_USER" ]; then
        note "WARNING: $APP_DIR/$dir is owned by $(stat -c '%U' "$APP_DIR/$dir"), not $SERVICE_USER"
        missing=1
      fi
    done
    if [ "$missing" = "1" ]; then
      note "the services will fail to write. Fix it with:"
      note "  sudo chown -R $SERVICE_USER:$SERVICE_GROUP $APP_DIR/data $APP_DIR/logs $APP_DIR/seeds $APP_DIR/target"
    fi
  fi
fi

# Everything below runs as the service user, with a PATH that already contains the
# places rustup and uv install into, because `sudo -u` does not read a login shell.
as_service_user() {
  sudo -u "$SERVICE_USER" -H \
    env "PATH=$SERVICE_HOME/.cargo/bin:$SERVICE_HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    "HOME=$SERVICE_HOME" "SEARCH_SKIP_SOUND=1" \
    bash -c "$1"
}

step "toolchain (rustup and uv) as $SERVICE_USER"
if as_service_user 'command -v cargo' >/dev/null 2>&1; then
  note "cargo $(as_service_user 'cargo --version' | awk '{print $2}')"
else
  note "installing the Rust toolchain into $SERVICE_HOME/.cargo"
  as_service_user "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable --no-modify-path" \
    | tail -3 | sed 's/^/    /'
fi
if as_service_user 'command -v uv' >/dev/null 2>&1; then
  note "uv $(as_service_user 'uv --version')"
else
  note "installing uv into $SERVICE_HOME/.local/bin"
  as_service_user "curl -LsSf https://astral.sh/uv/install.sh | sh" | tail -3 | sed 's/^/    /'
fi
as_service_user 'command -v cargo' >/dev/null 2>&1 || die "cargo is still not on $SERVICE_USER's PATH"
as_service_user 'command -v uv' >/dev/null 2>&1 || die "uv is still not on $SERVICE_USER's PATH"

step "building (this compiles RocksDB, so the first run takes a few minutes)"
as_service_user "cd '$APP_DIR' && ./scripts/build.sh" | sed 's/^/    /'

step "seed list"
if [ -s "$APP_DIR/seeds/official.txt" ]; then
  note "$(grep -cv '^#' "$APP_DIR/seeds/official.txt" || true) URLs already in seeds/official.txt"
else
  note "building one from the official sites' own sitemaps"
  as_service_user "cd '$APP_DIR' && uv run python scripts/make_seeds.py --limit 3000" | sed 's/^/    /'
fi

step "configuration at $ENV_FILE"
if [ -f "$ENV_FILE" ]; then
  note "already there -- left untouched (edit it and restart the services to change it)"
else
  cp "$ENV_TEMPLATE" "$ENV_FILE"
  chmod 0644 "$ENV_FILE"
  note "written from deploy/mjlsearch.env.example"
fi
# shellcheck disable=SC1090
. "$ENV_FILE" 2>/dev/null || true

step "systemd units"
units=()
for unit in mjlsearch-api mjlsearch-searchui mjlsearch-dashboard; do
  src="$UNIT_DIR/$unit.service"
  [ -f "$src" ] || die "missing unit template $src"
  sed -e "s|@APPDIR@|$APP_DIR|g" \
      -e "s|@SERVICE_USER@|$SERVICE_USER|g" \
      -e "s|@SERVICE_GROUP@|$SERVICE_GROUP|g" \
      -e "s|@SERVICE_HOME@|$SERVICE_HOME|g" \
      "$src" > "/etc/systemd/system/$unit.service"
  units+=("$unit")
  note "installed /etc/systemd/system/$unit.service"
done

if [ "$CRAWL" = "1" ]; then
  sed -e "s|@APPDIR@|$APP_DIR|g" \
      -e "s|@SERVICE_USER@|$SERVICE_USER|g" \
      -e "s|@SERVICE_GROUP@|$SERVICE_GROUP|g" \
      -e "s|@SERVICE_HOME@|$SERVICE_HOME|g" \
      "$UNIT_DIR/mjlsearch-crawl.service" > "/etc/systemd/system/mjlsearch-crawl.service"
  units+=(mjlsearch-crawl)
  note "installed /etc/systemd/system/mjlsearch-crawl.service"
else
  note "skipping the crawl unit (--no-crawl)"
fi

systemctl daemon-reload
systemctl enable "${units[@]}" >/dev/null
note "enabled: ${units[*]}"

if [ "$START" = "1" ]; then
  step "starting"
  systemctl restart mjlsearch-api.service
  # The pages read the API, so the wait is on the API being up rather than on a sleep.
  waited=0
  while [ "$waited" -lt 60 ]; do
    if curl -fsS -m 2 -o /dev/null "http://127.0.0.1:${SEARCH_PORT:-8000}/health"; then break; fi
    waited=$((waited + 1))
    sleep 1
  done
  if [ "$waited" -ge 60 ]; then
    note "the API did not answer within 60s -- journalctl -u mjlsearch-api -n 50"
  else
    note "API up at http://127.0.0.1:${SEARCH_PORT:-8000}/health"
  fi
  for unit in mjlsearch-searchui mjlsearch-dashboard; do
    systemctl restart "$unit.service"
  done
  if [ "$CRAWL" = "1" ]; then
    systemctl restart mjlsearch-crawl.service
  fi
  sleep 2
  systemctl --no-pager --lines=0 status "${units[@]}" | sed 's/^/    /' || true
else
  step "not starting (--no-start)"
  note "start everything with: systemctl start ${units[*]}"
fi

host_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
step "done"
cat <<EOF
    search page   http://${host_ip:-<server-ip>}:${SEARCH_UI_PORT:-5001}/
    growth page   http://${host_ip:-<server-ip>}:${SEARCH_UI_PORT:-5001}/stats
    API           http://127.0.0.1:${SEARCH_PORT:-8000}/docs      (loopback only)
    console       http://127.0.0.1:${SEARCH_DASHBOARD_PORT:-5000}/   (loopback only)

    config        $ENV_FILE              (ports, host, ranking knobs)
    logs          journalctl -u mjlsearch-api -f
                  journalctl -u mjlsearch-crawl -f
    status        systemctl status mjlsearch-api mjlsearch-searchui mjlsearch-dashboard mjlsearch-crawl
    update        git pull && sudo ./deploy/setup-server.sh
    stop          sudo systemctl disable --now mjlsearch-{api,searchui,dashboard,crawl}.service

    The page is the only service bound to every interface; the API and the console are
    loopback-only because neither has authentication. If a firewall is running, allow
    ${SEARCH_UI_PORT:-5001}/tcp:   sudo ufw allow ${SEARCH_UI_PORT:-5001}/tcp
EOF
